- name: Install Supervisor
  apt:
    name: supervisor
    state: present

- name: Add application supervisor config
  copy:
    dest: /etc/supervisor/conf.d/bookshelf.conf
    content: |
      [program:bookshelf]
      command=/home/alok_kumar_chauhann/.pyenv/shims/gunicorn -b 0.0.0.0:8080 main:app
      directory=/home/alok_kumar_chauhann/opt/project-bookshelf/7-gce
      autostart=true
      autorestart=true
      stderr_logfile=/var/log/bookshelf.err.log
      stdout_logfile=/var/log/bookshelf.out.log
      user=alok_kumar_chauhann

- name: Reload and update Supervisor
  shell: |
    supervisorctl reread
    supervisorctl update
    supervisorctl start bookshelf || true
